<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>


<div style="width: 100%;">

<div style="width:100%;height:450px;">

<div style="width:100%;height:40px;    border: 1px solid #ced4da;border-bottom: none"> 

<div style="width:50%;float:left;height:100%;border-radius: 0.25rem;">

<select class="custom-select">
  <option selected>Open this select menu</option>
  <option value="1">One</option>
  <option value="2">Two</option>
  <option value="3">Three</option>
</select>

</div>

<div style="width:50%;float:left;">
<select class="custom-select">
  <option selected>Open this select menu</option>
  <option value="1">One</option>
  <option value="2">Two</option>
  <option value="3">Three</option>
</select>
</div>


</div>
<div style="width:100%;height:350px;">

<div style="width:50%;float:left;height:150px;">
<textarea class="form-control" id="metin" name="metin" maxlength="128" required></textarea> 
</div>



 <div style="width:50%;float:left;height:150px;">
 <textarea class="form-control" id="metin" name="metin" maxlength="128" required></textarea> 
 </div>


</div>
</div>

</div>

<div class="modal left" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>