<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>



<!--Mainbody   -->
<div style="width:100%;height:100%;">

<!--Header   -->
<div style="width:100%;height:40px;"> 

<div style="width:49%;float:left;height:100%;">
<select class="custom-select">
  <option selected>Open this select menu</option>
  <option value="1">One</option>
  <option value="2">Two</option>
  <option value="3">Three</option>
</select>
</div>

<div style="width:50%;float:left;"> <i id="exchange" class="fas fa-exchange-alt" style="cursor: pointer;"></i>
<select class="custom-select">
  <option selected>Open this select menu</option>
  <option value="1">One</option>
  <option value="2">Two</option>
  <option value="3">Three</option>
</select>
</div>

</div>
<!--Header   -->

<!--Textarea   -->
<div style="width:100%;height:150px;">

<div style="width:50%;float:left;height:100%;">
<textarea class="form-control" id="metin" name="metin" maxlength="128" required></textarea> 
</div>

<div style="width:50%;float:left;height:100%;">
<textarea class="form-control" id="metin" name="metin" maxlength="128" required></textarea> 
</div>

</div>
<!--Textarea   -->

<!--Çevir   -->
<div class="col-md-12 text-center" style="padding-bottom: 50px;padding-top: 20px;">
<button id="translate" class="btn btn-primary mb-3">Çevir</button> 
</div>
<!--Çevir   -->

<!--Icons   -->
<div class="col-md-12 text-center"> 
<button class="withimg" id="history"><i class="fas fa-history"></i><br>Geçmiş</button>   
<button class="withimg" id="favs"><i class="fas fa-star"></i><br>Kaydedilenler</button>
</div>
<!--Icons   -->

</div>
<!--Mainbody   -->

<script>
$('#translate').click(function() {
console.log('translate');
});

$('#history').click(function() {
console.log('history');
});


$('#favs').click(function() {
console.log('favorite');
});

$('#exchange').click(function() {
console.log('exchange');
});





</script>