<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>


<?php  if($tip=='his'){ echo '
<div class="clearallcontainer">
<button class="clearall">Tümünü Temizle</button>
</div>';} ?>


<ul class="list-group">

<?php if(!empty($dizi)){ $dizi = array_reverse($dizi,true);
    foreach ($dizi as $key=>$row) { 
        echo '<li id="li'.$key.'" class="list-group-item d-flex justify-content-between align-items-center">
        <div class="content">
        <p style="margin-bottom:14px">'.$row['source'].'<i class="fas fa-arrow-right"></i>'.$row['target'].'</p>
        <p class="mb-1">'.$row['content'].'</p>
        <p style="color:#8b8f94">'.$row['translate'].'</p>
        </div>
        <div class="btn-group" style="align-self:flex-start">'; ?>
        <?php if($tip=='his'){ echo '<button  id="'.$tip.$key.'" class="'.$row['class'].'"><i class="fas fa-save" ></i></button>';} 
        echo '<button class="btn btn-danger" id="'.$tip.$key.'"><i class="fas fa-trash-alt"></i></button>
        </div>
        </li>';
    }}
?>

</ul>


