<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<?php 
for($a=count($dizi)-1;$a>=0;$a--){

    // echo $dizi[$a]['source'].'----->'.$dizi[$a]['target'].'<br><br>'.
    // $dizi[$a]['content'].'<br>'.$dizi[$a]['translate'].'<br><hr>';  btn btn-success mr-1
}?>

<div class="clearallcontainer">
<button class="clearall">Tümünü Temizle</button>
</div>


<ul class="list-group">

<?php for($a=count($dizi)-1;$a>=0;$a--){   
echo '<li class="list-group-item d-flex justify-content-between align-items-center">
<div class="content">
<p style="margin-bottom:14px">'.$dizi[$a]['source'].'<i class="fas fa-arrow-right"></i>'.$dizi[$a]['target'].'</p>
<p class="mb-1">'.$dizi[$a]['content'].'</p>
<p style="color:#8b8f94">'.$dizi[$a]['translate'].'</p>
</div>
<div class="btn-group" style="align-self:flex-start">
<button class="'.$dizi[$a]['class'].'"><i class="fas fa-save" ></i></button>
<button class="btn btn-danger"><i class="fas fa-trash-alt"></i></button>
</div>
</li>';
}?>

</ul>


